[tools]
gitleaks = "latest"
just = "latest"
prettier = "latest"
ruff = "latest"
bun = "latest"
node = "latest"
pnpm = "latest"
pkl = "latest"
shfmt = "latest"
shellcheck = "latest"

[env]
HK_MISE = 1
HK_LIBGIT2 = 0
MISE_NPM_BUN = 1
