[package]
name = "pixi_cuda_c"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "*" }

[package.build.config]
extra-args = ["-DCMAKE_BUILD_TYPE=Release", "-DTORCH_CUDA_ARCH_LIST='8.6'"]

# you need cuda-toolkit in build-dep or you'll get an error at link time: ld can't find libmvec.so
# you need cudnn/cusparse etc in host-deps or torch's cmake can't find em during cmake configure/build file generation
# pixi shows a "warning: overdepending on lubcudss" but it is necessary
[package.build-dependencies]
gcc = "*"
cmake = "*"
ninja = "*"
cuda-toolkit = ">=13.2"

[package.host-dependencies]
python = ">=3.11"
pytorch-gpu = "*"
nanobind = "*"

cuda-version =">=13.2"
cuda = ">=13.2"
cusparselt-dev = "*"
libcusparse-dev = "*"
libcudss-dev = "*"

[package.run-dependencies]
python = ">=3.11"
pytorch-gpu = "*"
