[workspace]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[dependencies]
pixi = { path = "." }
python = ">=3.13"
mojo = ">=25.5.0,<26"

[tasks]
start = "python -c 'import pixi as b; print(b.add(1, 2))'"

[package]
name = "pixi"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "*" }

[package.build.config]
extra-args = ["-DCMAKE_BUILD_TYPE=Release", "-DPYTHON_SOABI='cpython-313'"]

[package.host-dependencies]
ninja = ">=1.13.1"
cmake = ">=4.1.1"
gcc = ">=14.3.0,<14.4"
nanobind = ">=2.9.2"
python = ">=3.13"
python-abi3 = ">=3.13"

[feature.dev.dependencies]
pixi-pycharm = "*"

[environments]
default = { features = ["dev"], solve-group = "main" }
