[package]
name = "csrc"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "*" }

[package.build.config]
extra-args = ["-DCMAKE_BUILD_TYPE=Release", "-DTORCH_CUDA_ARCH_LIST='8.6'"]

[package.host-dependencies]
cuda = ">=12.9"
ninja = ">=1.13.1"
cmake = ">=4.1.1"
gcc = ">=14.3.0,<14.4"
clang = ">=21.1.1"
nanobind = ">=2.9.2"
python = ">=3.13"
pytorch-gpu = ">=2.8.0,<3"
